export { default as Background } from './Background/Background'
export { default as MazeBackground } from './MazeBackground/MazeBackground'
export { default as SocialSideBar } from './SocialSideBar/SocialSideBar'
export { default as SideBar } from './SideBar/SideBar'
export { default as IconImage } from './IconImage/IconImage'
